.Dd July 10, 1998
.Dt DAEMON 1 LOCAL
.Sh NAME
.Nm daemon
.Nd "run a process detached from the controlling tty"
.Sh SYNOPSIS
.Nm daemon
.Op Fl cf
.Ar program options
.Sh DESCRIPTION
.Nm Daemon
will run a given program detached from the controlling tty.  
The following options are recognized.
.Bl -tag -width 8n
.It Fl c
Before starting, change directories to the root directory
.It Fl f
Before starting, redirect the standard input, output and error to 
.Ar /dev/null 
.Sh HISTORY
A 
.Nm daemon function call first appeared in 4.4BSD.
.Sh WEBSITE
For more information, please see
.Ar http://github.com/howardjp/daemon .
.Sh SEE ALSO
.Xr nohup 1 ,
.Xr daemon 3

